# 메인 rust 도커 이미지를 사용한다
FROM rust as build

# app을 도커 이미지에 복사한다.
COPY . /app

# 작업 디렉터리를 복사한다
WORKDIR /app

# 앱을 빌드한다
RUN cargo build --release
# goolge distroless를 런타임 이미지로 사용한다.
FROM gcr.io/distroless/cc-debian11

# 빌더에서 앱을 복사한다.
COPY --from=build /app/target/release/docker-rust /app/docker-rust
WORKDIR /app

# 애플리케이션을 시작한다
CMD ["./docker-rust"]